name: Publish image
# Run the tasks on every push that changes the images
on:
  push:
    paths:
      - .github/workflows/build-push-images.yaml
      - images/**
jobs:
  push_to_registry:
    name: Push images to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker layer caching
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build builder image
        uses: docker/build-push-action@v2
        with:
          context: ./images/build
          platforms: linux/amd64,linux/arm64
          push: false
          # Just tag it with the tag expected by the server and client
          tags: ghcr.io/stackhpc/tunnel-build:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Meta for server image
        id: server-meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/stackhpc/tunnelto-server
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=

      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: ./images/server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.server-meta.outputs.tags }}
          labels: ${{ steps.server-meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Meta for client image
        id: client-meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/stackhpc/tunnelto-client
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=

      - name: Build and push client image
        uses: docker/build-push-action@v2
        with:
          context: ./images/client
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.client-meta.outputs.tags }}
          labels: ${{ steps.client-meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      # https://github.com/docker/buildx/pull/535
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
